In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\khushi pawar\Downloads\customer.csv")

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df=df.iloc[:,2:]

In [5]:
df.sample(5)

review education purchased
15     Poor        UG        No
37  Average        PG       Yes
38     Good    School        No
34  Average    School        No
18     Good    School        No

In [6]:
df.shape

(50, 3)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

X_train.shape
y_train.shape

(40,)

In [8]:
X_train

review education
5   Average    School
23     Good    School
35     Poor    School
32  Average        UG
13  Average    School
11     Good        UG
41     Good        PG
20  Average    School
40     Good    School
1      Poor        UG
4   Average        UG
47     Good        PG
38     Good    School
0   Average    School
12     Poor    School
15     Poor        UG
7      Poor    School
44  Average        UG
30  Average        UG
31     Poor    School
49     Good        UG
14     Poor        PG
45     Poor        PG
25     Good    School
2      Good        PG
16     Poor        UG
39     Poor        PG
8   Average        UG
10     Good        UG
3      Good        PG
29  Average        UG
48     Good        UG
19     Poor        PG
21  Average        PG
27     Poor        PG
22     Poor        PG
34  Average    School
43     Poor        PG
6      Good    School
42     Good        PG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [13]:
X_train

array([[1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.]])

In [14]:
X_test

array([[0., 2.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [2., 2.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()

In [18]:
y_train

5     Yes
23     No
35    Yes
32    Yes
13     No
11    Yes
41    Yes
20    Yes
40     No
1      No
4      No
47    Yes
38     No
0      No
12     No
15     No
7     Yes
44     No
30     No
31    Yes
49     No
14    Yes
45    Yes
25     No
2      No
16    Yes
39     No
8      No
10    Yes
3      No
29    Yes
48    Yes
19    Yes
21     No
27     No
22    Yes
34     No
43     No
6      No
42    Yes
Name: purchased, dtype: object

In [19]:
le.fit(y_train)

LabelEncoder()

In [20]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [21]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1])

In [22]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 1])